version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      node-dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: 'typescript'
      - dependency-name: 'zone.js'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'