version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      angular-dependencies:
        patterns:
          - '@angular*'
          - '@cypress/schematic'
          - 'rxjs'
          - 'tslib'
          - 'zone.js'
          - '@types/jasmine'
          - 'jasmine-core'
          - 'karma*'
          - 'typescript'
      ngneat-dependencies:
        patterns:
          - '@ngneat*'
      css-dependencies:
        patterns:
          - 'bootstrap*'
          - 'flag-icons'
      eslint-dependencies:
        patterns:
          - 'angular-eslint'
          - 'eslint'
          - 'typescript-eslint'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'node'
        versions: ['~> 23']

  - package-ecosystem: 'docker-compose'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'eclipse-temurin'
        versions: ['~> 22']