version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      angular-dependencies:
        patterns:
          - '@angular*'
          - '@cypress/schematic'
          - 'rxjs'
          - 'tslib'
          - 'zone.js'
          - '@types/jasmine'
          - 'jasmine-core'
          - 'karma*'
          - 'typescript'
      ngneat-dependencies:
        patterns:
          - '@ngneat*'
      eslint-dependencies:
        patterns:
          - 'angular-eslint'
          - 'eslint'
          - 'typescript-eslint'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'docker-compose'
    directory: '/'
    schedule:
      interval: 'monthly'