name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'daniel2202x/ngx-todo'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install NPM packages
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run Cypress tests
        run: npm run cypress:docker
      
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
